# Generated by Django 3.0.2 on 2020-03-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='mag/'),
        ),
    ]
