# Generated by Django 3.0.2 on 2020-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadf', '0002_auto_20200309_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='mag/cover/'),
        ),
    ]
